### PR TITLE
nginx tuning in lieu of http/2

### PR DESCRIPTION
**Pull request by mchangrh**
- whitespace formatting
- added keepalive
- buffer access_logs
- friendship ended with http/2, nginx is my new best friend ([#420](https://github.com/ajayyy/SponsorBlockServer/issues/420#issuecomment-997301080))

documentation re: keepalive https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive

### CODE REVIEW

**Comment by ajayyy** [comment]
So, from my reading

keepalive -> reuse connections between consecutive requests

http2 -> allows reusing connections between concurrent requests

And this config only changes the keepalive to upsteam servers, not to clients, so it should be it should reduce unused connections hanging around (so hopefully will solve the issue).

**Comment by mchangrh** [comment]
keepalive -> reuse socket + connection for connections to upstream

http2 -> combine multiple (connections + sockets) into one

the config only adds keepalive for upstream/proxy

**Comment by mchangrh** [comment]
it will reduce the number of upstream unused connections hanging around, sysctl tuning takes care of outgoing ones

**Comment by ajayyy** [comment]
Fixes to make this config valid: https://github.com/ajayyy/SponsorBlockServer/commit/f54b9f7ae1cb6e152fe485223e4ff5f2a6cd1884

**Pull request merged**
