### PR TITLE
add ETag to skipSegments byHash

### LINKED ISSUE #527: Change occurred endpoint
Right now refetch if not found uses way too much bandwidth due to randomizing of the results breaking the etag cache header 304. A better option would be to have a change occurred endpoint

### PR DESCRIPTION
**Pull request by mchangrh**
- [x] I agree to license my contribution under AGPL-3.0-only with my contribution automatically being licensed under LGPL-3.0 additionally after 6 months

***

closes #527

### CODE REVIEW

**Comment by mchangrh** [comment]
added on some changes since they happened to coincide with ETag

 - locked npm run docker containers to version in docker-compose
 - disabled native eTag handling
 - moved categories/actionTypes/reqSegments parsing to standalone function
   - there were slight differences in validation and a lot of duplicate code
   - this way the invalid syntax JSON error can be properly handled
 - moved oldGetSkipSegments into getSkipSegments.ts
   - the old method of splitting the getSkipSegments into endpoint and the actual segments made eTag almost impossible to implement
- viewedVideoSponsorTime
  - Boolean instead of == undefined, conditional operator for UUID
- redis
  - add TTL command to RedisSB (duh)
- queryCacher
  - add getKeyLastModified

**Comment by mchangrh** [comment]
PR is ready but needs a complimenting extension upgrade as well

**Comment by ajayyy** [comment]
Is this fine to merge even without client changes?

**Comment by mchangrh** [comment]
yes it should work even without client support, it will generate etags but likely not be used.

**Pull request merged**
