### PR TITLE
Composite Actions

### PR DESCRIPTION
**Pull request by mchangrh**
https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/

### CODE REVIEW

**Comment by ajayyy** [comment]
Nice!

**Comment by ajayyy** [comment]
Why isn't the CI running on this PR?

**Comment by mchangrh** [comment]
New CIs need author approval, it's a security setting

image

**Comment by ajayyy** [comment]
hmm, I have it set to that, and normally it asks for approval beside the merge button

image

**Comment by mchangrh** [comment]
I can try it in my fork

**Comment by mchangrh** [comment]
getting errors on fork, will undraft once they're ironed out

**Comment by ajayyy** [comment]
Could be because of the repo url causing it to pull node-setup from master branch?

**Comment by mchangrh** [comment]
seems to also be a syntax error, I'll try in a different repo

**Comment by mchangrh** [comment]
Composite actions are shell-only which would only save `npm i`

**Pull request closed without merging**
