### PR TITLE
Fix leaderboard

### PR DESCRIPTION
**Pull request by MRuy**
Fixed leaderboard by replacing `ISNULL` with postgres `COALESCE` and coping `shadowBannedUsers` table from `privateDB` database to a temporary table in the main database and remove it again.

### CODE REVIEW

**Comment by ajayyy** [comment]
Since the db export is now exporting specific tables from the config, maybe we can keep this in the public db now?

**Comment by MRuy** [comment]
Yes, i think it would be good to have the `privateDB` database tables inside the main database, maybe prefix them with `private_`

**Comment by ajayyy** [comment]
Non-js solution https://stackoverflow.com/a/39012075/1985387

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlockServer/commit/f6d79616a43a7da74bb3cf3465ab83686b418511

**Pull request closed without merging**
