### PR TITLE
Limit reward time per segment

### PR DESCRIPTION
**Pull request by MRuy**

### CODE REVIEW

**Review by ajayyy — APPROVED** [review]

**Review by ajayyy — CHANGES_REQUESTED** [review]
Can you add this to the personal stats too?

**Review by ajayyy — APPROVED** [review]

**Comment by ajayyy** [comment]
@MRuy Can you review my merge conflict fix?

**Review by MRuy — COMMENTED** [review]
Looks good from my side

**Comment by ajayyy** [comment]
That actually matters in postgres. Single quote = string, double quote = identifier.

**Pull request merged**
